# Generated by Django 3.1.5 on 2021-02-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
